[build]
  publish = "new"
  command = "echo 'Static site, no build needed'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/new/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/new/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[dev]
  publish = "new"
  functions = "netlify/functions"